import { TestSession } from '../types/aut';

/**
 * Generates a clean, comprehensive structured text/markdown summary of the session.
 */
export function generateStructuredTextSummary(session: TestSession): string {
  const { item, scores, completedInSeconds, ideas, date } = session;
  const dateFormatted = new Date(date).toLocaleString();

  const ideasList = ideas
    .map((idea, index) => {
      const tag = idea.rarityTag ? ` [${idea.rarityTag}]` : '';
      const cat = ` (${idea.category})`;
      return `${index + 1}. "${idea.text}"${cat}${tag} - Originality: ${idea.originalityScore}/100`;
    })
    .join('\n');

  const categoriesList = Object.entries(scores.flexibility.categoryDistribution)
    .filter(([_, count]) => count > 0)
    .map(([cat, count]) => `  • ${cat.charAt(0).toUpperCase() + cat.slice(1)}: ${count} idea${count > 1 ? 's' : ''}`)
    .join('\n');

  return `# DIVERGE. Alternative Uses Test (AUT) Analysis Report
Generated: ${dateFormatted}
Cognitive Protocol: J.P. Guilford's Divergent Thinking Battery (1967)

==================================================
1. CHALLENGE OBJECT
==================================================
• Name: ${item.name}
• Subtitle: ${item.subtitle}
• Category: ${item.category}
• Material: ${item.material}
• Dimensions: ${item.dimensions}
• Sprint Duration: ${completedInSeconds} seconds

==================================================
2. EXECUTIVE SUMMARY & COMPOSITE SCORE
==================================================
⭐ Composite Creative Index: ${scores.overallCreativeIndex} / 100
🎯 Key Focus Area: ${scores.designTakeaway.pillar} - ${scores.designTakeaway.headline}
💡 Cognitive Exercise: ${scores.designTakeaway.exercise}
🛠️ Design Method: ${scores.designTakeaway.method}
✨ Standout Concept: "${scores.mostUniqueIdea?.text || 'N/A'}"

==================================================
3. 4-PILLAR DIVERGENT THINKING BREAKDOWN
==================================================
[1] FLUENCY (Ideation Volume & Speed)
    • Score: ${scores.fluency.score} / 100
    • Total Ideas: ${ideas.length}
    • Ideation Speed: ${scores.fluency.ideasPerMinute} ideas/min
    • Benchmark Tier: ${scores.fluency.benchmarkTier}

[2] FLEXIBILITY (Cognitive Domain Switching)
    • Score: ${scores.flexibility.score} / 100
    • Unique Categories Spanned: ${scores.flexibility.uniqueCategoriesCount}
    • Dominant Category: ${scores.flexibility.dominantCategory}
    • Categories Distribution:
${categoriesList || '  • None'}

[3] ORIGINALITY (Statistical Novelty & Lateral Leaps)
    • Score: ${scores.originality.score} / 100
    • Lateral Non-Obvious Ideas: ${scores.originality.originalityRatio}%
    • Most Original Concept: "${scores.originality.mostOriginalIdea?.text || 'N/A'}"

[4] ELABORATION (Concept Specificity & Depth)
    • Score: ${scores.elaboration.score} / 100
    • Average Word Count: ${scores.elaboration.averageWordCount} words/idea
    • Action Verb Density: ${scores.elaboration.actionVerbDensity}

==================================================
4. COMPLETE IDEA LOG (${ideas.length} Entries)
==================================================
${ideasList || 'No ideas recorded.'}

==================================================
Report generated by DIVERGE. Studio
`;
}

/**
 * Generates a clean, typed JSON structure for external tracking (Notion, Obsidian, databases).
 */
export function generateSessionJSON(session: TestSession): string {
  const exportPayload = {
    schemaVersion: '1.0.0',
    exportedAt: new Date().toISOString(),
    protocol: "Guilford's Alternative Uses Test (AUT)",
    session: {
      id: session.id,
      timestamp: session.date,
      completedInSeconds: session.completedInSeconds,
      targetObject: {
        id: session.item.id,
        name: session.item.name,
        category: session.item.category,
        material: session.item.material,
        dimensions: session.item.dimensions
      },
      evaluation: {
        compositeCreativeIndex: session.scores.overallCreativeIndex,
        mostUniqueIdea: session.scores.mostUniqueIdea,
        designTakeaway: session.scores.designTakeaway,
        pillars: {
          fluency: {
            score: session.scores.fluency.score,
            totalIdeas: session.ideas.length,
            ideasPerMinute: session.scores.fluency.ideasPerMinute,
            benchmarkTier: session.scores.fluency.benchmarkTier
          },
          flexibility: {
            score: session.scores.flexibility.score,
            uniqueCategoriesCount: session.scores.flexibility.uniqueCategoriesCount,
            dominantCategory: session.scores.flexibility.dominantCategory,
            categoryDistribution: session.scores.flexibility.categoryDistribution
          },
          originality: {
            score: session.scores.originality.score,
            originalityRatio: session.scores.originality.originalityRatio,
            mostOriginalIdea: session.scores.originality.mostOriginalIdea
          },
          elaboration: {
            score: session.scores.elaboration.score,
            averageWordCount: session.scores.elaboration.averageWordCount,
            actionVerbDensity: session.scores.elaboration.actionVerbDensity
          }
        }
      },
      ideas: session.ideas.map((idea, idx) => ({
        index: idx + 1,
        id: idea.id,
        text: idea.text,
        timestampSeconds: idea.timestamp,
        category: idea.category,
        originalityScore: idea.originalityScore,
        elaborationScore: idea.elaborationScore,
        rarityTag: idea.rarityTag || 'Conventional',
        wordCount: idea.text.trim().split(/\s+/).length
      }))
    }
  };

  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Triggers a browser file download for text or json content.
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
